name: CI

on:
  
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Install dependencies
      run: npm install --prefix ./Client
    - name: Lint
      run:  npm run lint --prefix ./Client
    - name: Build
      run:  npm run build --prod --prefix ./Client
#     - name: Test
#       run: npm test -- --configuration=ci --prefix ./Client
#     - name: E2E
#       run: npm run e2e --prefix ./Client
